### ISSUE TITLE
FR-6: As a creator, I want to see a preview of the timeline. ENHANCEMENT

### ISSUE THREAD

**Issue by maiken-veedla** [krlkngro/interactive-timeline#23]
[FR-6: As a creator, I want to see a preview of the timeline, so I can see how the result would look like.](https://github.com/krlkngro/interactive-timeline/wiki/Requirements#fr-6-as-a-creator-i-want-to-see-a-preview-of-the-timeline-so-i-can-see-how-the-result-would-look-like)

Acceptance criteria:
- The preview updates always after editing, adding or removing a cell or rearranging cells. (3rd/4th iteration)
- The videos are playable. (3rd iteration)
- The cells are packable and unpackable. (4th iteration)
- "See more" in a cell is clickable and cell would expand. (4th iteration)

**Comment by mannapuder** [comment]
See PR #104
